import { StyleSheet } from "react-native";

export const colors = {
  accent: "#0000EE",
  bg: "#F4F6FB",
  surface: "#FFFFFF",
  text: "#0b1220",
  muted: "#5b6675",
  border: "rgba(12,18,32,0.12)",
  success: "#099268",
  error: "#D92D20",
  accentSoft: "rgba(0,0,238,0.10)",
  accentBorder: "rgba(0,0,238,0.22)",
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
};

export const pressedOpacity = 0.72;

export const cardShadow = {
  shadowColor: "#0b1220",
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.06,
  shadowRadius: 8,
  elevation: 2,
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  content: { padding: spacing.lg, paddingBottom: 40 },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    ...cardShadow,
  },
  title: { fontSize: 18, fontWeight: "700", color: colors.text, marginBottom: 4 },
  sectionTitle: { fontSize: 15, fontWeight: "700", color: colors.text, marginBottom: spacing.sm },
  subtitle: { fontSize: 13, color: colors.muted, marginBottom: spacing.md, lineHeight: 18 },
  label: { fontSize: 13, fontWeight: "600", color: colors.text, marginBottom: 6 },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.text,
    backgroundColor: colors.surface,
    marginBottom: spacing.md,
  },
  inputRO: { backgroundColor: "#ECEFF6", color: colors.muted },
  btn: {
    backgroundColor: colors.accent,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
  },
  btnText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  btnSoft: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 40,
  },
  btnSoftText: { color: colors.text, fontWeight: "600", fontSize: 13 },
  row: { flexDirection: "row", gap: spacing.sm, flexWrap: "wrap", marginTop: spacing.sm },
  listItem: {
    padding: 14,
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.sm,
    ...cardShadow,
  },
  listTitle: { fontSize: 15, fontWeight: "700", color: colors.text },
  listSub: { fontSize: 12, color: colors.muted, marginTop: 4 },
  badge: {
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 99,
    backgroundColor: colors.accentSoft,
    marginTop: 6,
  },
  badgeText: { fontSize: 10, fontWeight: "700", color: colors.accent, textTransform: "uppercase" },
  error: { color: colors.error, fontSize: 13, marginTop: spacing.sm },
  hint: { fontSize: 12, color: colors.muted, marginTop: 4 },
  fab: {
    position: "absolute",
    right: spacing.lg,
    bottom: spacing.lg,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    ...cardShadow,
    shadowOpacity: 0.15,
    elevation: 4,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 99,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  chipText: { fontSize: 12, fontWeight: "600", color: colors.accent },
});
